## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      julia: 0.7
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 1.0
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: nightly
      env: TESTCMD="xvfb-run julia"
  allow_failures:
    - julia: nightly

branches:
  only:
    - master
    - amphiDev

notifications:
  email: false

addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ffmpeg

# Build script copied from DrakeVisualizer -- probably not required here, but an transmitting the package requirements for clarity
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg; fi

# script:
#   - julia --color=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Arena")'
#   - $TESTCMD --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test("Arena", coverage=true)'
#   # - julia --color=yes -e 'using MeshCat; MeshCat.develop_meshcat_assets(true)'
#   # - julia --color=yes -e 'import Pkg; Pkg.build("MeshCat")'
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - TESTCMD --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'


after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
